#cloud-config
ssh_pwauth: true
disable_root: true

users:
  - name: rick
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users,admin
    home: /home/rick
    shell: /bin/bash
    lock_passwd: false
# Add your ssh key here
#    ssh-authorized-keys:
#      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC09wk3nMwVmZINZncM8TFRJumrfVxOT83o43T+h4LL ...

chpasswd:
  list: |
    rick:linux

# network configuration
hostname: aux
fqdn: aux.lan

# disks
growpart:
  mode: auto
  devices:
    - '/'

package_update: true
packages:
  - qemu-guest-agent
  - git
  - linux-image-4.15.0-45-lowlatency

# run commands
#runcmd:
#  - touch /etc/cloud/cloud-init.disabled
#  - git clone "https://gerrit.o-ran-sc.org/r/ric-plt/appmgr" /appmgr
#  - pip3 install /appmgr/xapp_orchestrater/dev/xapp_onboarder
#  - git clone http://gerrit.o-ran-sc.org/r/it/dep /ric
#  - cd /ric && git submodule update --init --recursive --remote
#  - cd /ric/tools/k8s/bin/ && ./gen-cloud-init.sh && ./k8s-1node-cloud-init-k_1_16-h_2_17-d_cur.sh
# k8s-1node...sh will reboot the system

power_state:
  mode: reboot
